services:
  # redis:
  #   image: redis:alpine
  #   ports: 
  #   - "6379:6379"
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: drf
    ports:
      - "5432:5432"
      
