# Generated by Django 5.2.7 on 2025-10-10 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
