# Generated by Django 5.2.6 on 2025-10-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_userpreferencesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='directors',
            field=models.JSONField(default=list),
        ),
    ]
